AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: MIT
Description: "Sky-As-Code organisation, AWS-As-Code repository.
  Create a VPC with IPv4 CIDR block, abided by following Common context: Single account compliance, Resource tagging compliance, AWS Region compliance.
  **NOTICE** You won't be billed for the AWS resources used if you create a stack from this template."
Parameters:
  # For Resource tagging compliance
  CostCenter:
    Description: The department code.
    Type: String
  EnvironmentType:
    Description: The deployment environment type.
    Type: String

  # For this stack
  VPCName:
    Description: Last part of VPC instance, it will be prepended with a prefix.
    Type: String
  NetworkAddressIpV4:
    Description: 'The IP address part of the CIDR block, before slash (/). E.g: 10.0.0.0'
    Type: String
  CidrBlockSizeIpV4:
    Description: 'The bits part of the CIDR block, after slash (/). E.g: 8, 16, 24'
    Type: Number
    MinValue: 8
    MaxValue: 30

Mappings:
  AllowedRegions:
    ap-southeast-1:
      Allowed: "true"
    eu-central-1:
      Allowed: "true"
    us-east-1:
      Allowed: "true"

Conditions:
  ShouldCreateVpc: !Not
    - !Equals
      - !FindInMap [AllowedRegions, !Ref "AWS::Region", Allowed]
      - ''

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Condition: ShouldCreateVpc
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Sub "${NetworkAddressIpV4}/${CidrBlockSizeIpV4}" # E.g: 10.0.0.0/16
      Tags:
        -
          Key: Name # E.g: fin-nonprod-services-v1, sec-prod-tooling-v123
          Value: !Join
            - '-'
            - - !Ref CostCenter
              - !Ref EnvironmentType
              - !Ref VPCName
        - Key: EnvironmentType
          Value: !Ref EnvironmentType

Outputs:
  VPCId:
    Description: VPCId of VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${CostCenter}-${EnvironmentType}-vpc-id" # E.g: fin-nonprod-vpc-id, sec-prod-vpc-id

  NetworkAddressIpV4:
    Description: 'The IP address part of the CIDR block, before slash (/). E.g: 10.0.0.0'
    Value: !Ref NetworkAddressIpV4
    Export:
      Name: !Sub "${CostCenter}-${EnvironmentType}-vpc-networkAddressIpV4" # E.g: fin-nonprod-vpc-networkAddressIpV4, sec-prod-vpc-networkAddressIpV4

  CidrBlockSizeIpV4:
    Description: 'The bits part of the CIDR block, after slash (/). E.g: 8, 16, 24'
    Value: !Ref CidrBlockSizeIpV4
    Export:
      Name: !Sub "${CostCenter}-${EnvironmentType}-vpc-cidrBlockSizeIpV4" # E.g: fin-nonprod-vpc-cidrBlockSizeIpV4, sec-prod-vpc-cidrBlockSizeIpV4
