AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  License: MIT
Description: "Sky-As-Code organisation, AWS-As-Code repository.
  Create a VPC abided by following Common context: Resource tagging compliance, AWS Region compliance.
  **NOTICE** You won't be billed for the AWS resources used if you create a stack from this template."
Parameters:
  # For Organisation compliance
  CostCenter:
    Description: The department code.
    Type: String
  EnvironmentType:
    Description: The deployment environment type.
    Type: String

  # For this stack
  VPCName:
    Description: Last part of VPC instance, it will be prepended with a prefix.
    Type: String
  NetworkAddressIpV4:
    Description: 'The IP address part of the CIDR, before slash (/). E.g: 10.0.0.0'
    Type: String
  CidrBlockSizeIpV4:
    Description: 'The bits part of the CIDR, after slash (/). E.g: 8, 16, 24'
    Type: Number
    MinValue: 8
    MaxValue: 30

Mappings:
  # This mapping accounts for the scenario when certain AZs
  # are not available to use (this differs on a per account
  # per customer basis). E.g., if the 'c' AZ is not available
  # in a specific region in one's account then updating the
  # list contained in the mapping below here will allow a
  # different AZ to be chosen.
  AzRegions:
    ap-southeast-1:
      AZs: [b, c]
    eu-central-1:
      AZs: [a, b]
    us-east-1:
      AZs: [d, e]

Conditions:
  ShouldCreateVpc: !Not
    - !Equals
      - !Select [0, !FindInMap [AzRegions, !Ref "AWS::Region", AZs] ]
      - ''

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Condition: ShouldCreateVpc
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Sub "${NetworkAddressIpV4}/${CidrBlockSizeIpV4}" # E.g: 10.0.0.0/16
      Tags:
        -
          Key: Name # E.g: fin-nonprod-services-v1, sec-prod-tooling-v123
          Value: !Join
            - '-'
            - - !Ref CostCenter
              - !Ref EnvironmentType
              - !Ref VPCName
        - Key: EnvironmentType
          Value: !Ref EnvironmentType

  IPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
        AmazonProvidedIpv6CidrBlock: true
        VpcId: !Ref VPC

Outputs:
  VPCId:
    Description: VPCId of VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "vpc-${CostCenter}-${EnvironmentType}-id" # E.g: vpc-fin-nonprod-id, vpc-sec-prod-id

  NetworkAddressIpV4:
    Description: 'The IP address part of the IPv4 CIDR block, before slash (/). E.g: 10.0.0.0'
    Value: !Ref NetworkAddressIpV4
    Export:
      Name: !Sub "vpc-${CostCenter}-${EnvironmentType}-networkAddressIpV4" # E.g: vpc-fin-nonprod-networkAddressIpV4, vpc-sec-prod-networkAddressIpV4

  CidrBlockSizeIpV4:
    Description: 'The bits part of the IPv4 CIDR block, after slash (/). E.g: 8, 16, 24'
    Value: !Ref CidrBlockSizeIpV4
    Export:
      Name: !Sub "vpc-${CostCenter}-${EnvironmentType}-cidrBlockSizeIpV4" # E.g: vpc-fin-nonprod-cidrBlockSizeIpV4, vpc-sec-prod-cidrBlockSizeIpV4

  NetworkAddressIpV6:
    Description: 'The IP address part of the IPv6 CIDR block, before slash (/). E.g: 2001:db8:1234:1a00::, 2406:da18:f21:d900:0:0:0:0'
    Value: !Select
      - 0
      - !Split
        - '/'
        - !Select [ 0, !Cidr [ !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks], 1, 56 ]] # The IPv6 CIDR block size is fixed at /56
    Export:
      Name: !Sub "vpc-${CostCenter}-${EnvironmentType}-networkAddressIpV6" # E.g: vpc-fin-nonprod-networkAddressIpV6, vpc-sec-prod-networkAddressIpV6

  CidrBlockSizeIpV6:
    Description: 'The bits part of the IPv6 CIDR block, after slash (/). E.g: 56, 64'
    Value: '56'
    Export:
      Name: !Sub "vpc-${CostCenter}-${EnvironmentType}-cidrBlockSizeIpV6" # E.g: vpc-fin-nonprod-cidrBlockSizeIpV6, vpc-sec-prod-cidrBlockSizeIpV6
